version: '3.8'

services:
  server:
    build: .
    ports:
      - 3000:3000
    volumes:
      - "./src/:/usr/app/src"
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      ARCHITECTURE: monolith

  mongo:
    image: mongo:4.4.4-bionic
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks: 
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
